#!/usr/bin/env python3
"""Deterministic helpers for a Domain Knowledge Bundle.

Implements the machine-checkable part of references/bundle-contract.md:
validate, index, stale, proposals, inventory, audit, lock/unlock, init, log.
No third-party dependencies; frontmatter is parsed with a small YAML subset
parser so the script runs on a bare python3.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

# --------------------------------------------------------------------------- #
# Contract constants (mirror bundle-contract.md)
# --------------------------------------------------------------------------- #

BUSINESS_TYPES = {
    "Bounded Context",
    "Ubiquitous Term",
    "Business Capability",
    "Business Process",
    "Business Rule",
    "Domain Event",
    "Context Relationship",
}
SKELETON_TYPES = {"Repository", "Application", "Module"}
DETAIL_TYPES = {"API Endpoint", "Event Channel", "Data Model", "Configuration"}
DECISION_TYPES = {"Architecture Decision", "Playbook", "Reference"}
ALL_TYPES = BUSINESS_TYPES | SKELETON_TYPES | DETAIL_TYPES | DECISION_TYPES
HUMAN_VERIFIED_TYPES = BUSINESS_TYPES | {"Architecture Decision"}

STATUSES = {"draft", "stable", "deprecated"}
VIEWS = {"as-is", "to-be", "historical"}
ROLES = {
    "implementation",
    "test-observation",
    "runtime-observation",
    "contract",
    "design-intent",
    "business-policy",
    "human-confirmation",
    "historical",
}
REQUIRED_FIELDS = ("type", "title", "description", "context", "view", "owner", "sources", "status")

TYPE_DIR = {
    "Ubiquitous Term": "glossary",
    "Business Capability": "capabilities",
    "Business Process": "processes",
    "Business Rule": "rules",
    "Domain Event": "events",
    "Context Relationship": "relationships",
    "Repository": "repositories",
    "Module": "modules",
    "API Endpoint": "interfaces",
    "Event Channel": "events",
    "Data Model": "data-models",
    "Configuration": "configurations",
    "Architecture Decision": "decisions",
    "Playbook": "playbooks",
    "Reference": "references",
}

PROPOSAL_KINDS = {"conflict", "refine", "new", "route-error", "stale"}
QUEUE_KINDS = {"route-error", "stale"}

KEBAB = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*\.md$")
LINK = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)\)")
GENERATED_MARK = "<!-- generated by kb.py index -->"
SKIP_NAMES = {"index.md", "log.md"}

# --------------------------------------------------------------------------- #
# Bundle discovery
# --------------------------------------------------------------------------- #


def find_bundle_root(start: Path | None = None) -> Path | None:
    """Resolve the bundle root: env, .domain-kb pointer, ./domain-kb, or cwd."""
    env = os.environ.get("DOMAIN_KB_ROOT")
    if env and (Path(env) / "knowledge").is_dir():
        return Path(env).resolve()
    base = (start or Path.cwd()).resolve()
    pointer = base / ".domain-kb"
    if pointer.is_file():
        target = (base / pointer.read_text(encoding="utf-8").strip()).resolve()
        if (target / "knowledge").is_dir():
            return target
    for candidate in (base / "domain-kb", base):
        if (candidate / "knowledge" / "index.md").is_file() or (candidate / ".kb").is_dir():
            return candidate
    return None


def require_bundle(path_arg: str | None) -> Path:
    root = Path(path_arg).resolve() if path_arg else find_bundle_root()
    if root is None or not (root / "knowledge").is_dir():
        sys.exit("bundle root not found; pass --bundle or run kb.py init")
    return root


# --------------------------------------------------------------------------- #
# Frontmatter (YAML subset)
# --------------------------------------------------------------------------- #


class ParseError(ValueError):
    pass


def split_frontmatter(text: str) -> tuple[str | None, str]:
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---", 4)
    if end == -1:
        raise ParseError("unterminated frontmatter")
    return text[4:end], text[end + 4 :].lstrip("\n")


def _strip_comment(line: str) -> str:
    if '"' in line or "'" in line:
        return line
    return re.sub(r"\s#.*$", "", line)


def _scalar(raw: str) -> Any:
    value = raw.strip()
    if value in ("", "~", "null"):
        return None
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_scalar(part) for part in re.split(r",\s*", inner)]
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value == "true":
        return True
    if value == "false":
        return False
    return value


def _split_kv(s: str) -> tuple[str, str]:
    match = re.match(r"^([A-Za-z0-9_.-]+):(?:\s+(.*))?$", s)
    if not match:
        raise ParseError(f"cannot parse mapping line: {s!r}")
    return match.group(1), (match.group(2) or "")


def parse_yaml_subset(text: str) -> dict:
    lines = [_strip_comment(l.rstrip()) for l in text.splitlines()]
    lines = [l for l in lines if l.strip() and not l.strip().startswith("#")]
    pos = 0

    def indent_of(line: str) -> int:
        return len(line) - len(line.lstrip(" "))

    def parse_block(indent: int) -> Any:
        nonlocal pos
        result: Any = None
        while pos < len(lines):
            line = lines[pos]
            cur = indent_of(line)
            if cur < indent:
                break
            if cur > indent:
                raise ParseError(f"unexpected indent: {line!r}")
            stripped = line.strip()
            if stripped.startswith("- ") or stripped == "-":
                if result is None:
                    result = []
                if not isinstance(result, list):
                    raise ParseError(f"mixed list and mapping at: {line!r}")
                item = stripped[1:].strip()
                pos += 1
                if item and re.match(r"^[A-Za-z0-9_.-]+:(\s|$)", item):
                    key, value = _split_kv(item)
                    entry: dict = {}
                    if value == "":
                        if pos < len(lines) and indent_of(lines[pos]) > indent + 2:
                            entry[key] = parse_block(indent_of(lines[pos]))
                        else:
                            entry[key] = None
                    else:
                        entry[key] = _scalar(value)
                    if pos < len(lines) and indent_of(lines[pos]) == indent + 2:
                        more = parse_block(indent + 2)
                        if isinstance(more, dict):
                            entry.update(more)
                    result.append(entry)
                else:
                    result.append(_scalar(item))
            else:
                if result is None:
                    result = {}
                if not isinstance(result, dict):
                    raise ParseError(f"mixed list and mapping at: {line!r}")
                key, value = _split_kv(stripped)
                pos += 1
                if value == "":
                    if pos < len(lines) and indent_of(lines[pos]) > indent:
                        result[key] = parse_block(indent_of(lines[pos]))
                    else:
                        result[key] = None
                else:
                    result[key] = _scalar(value)
        return result if result is not None else {}

    parsed = parse_block(0)
    if not isinstance(parsed, dict):
        raise ParseError("frontmatter must be a mapping")
    return parsed


def read_concept(path: Path) -> tuple[dict | None, str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if text.startswith(GENERATED_MARK):
        return None, text
    fm_text, body = split_frontmatter(text)
    if fm_text is None:
        return None, body
    return parse_yaml_subset(fm_text), body


# --------------------------------------------------------------------------- #
# Concept enumeration
# --------------------------------------------------------------------------- #


def iter_concepts(knowledge: Path):
    for path in sorted(knowledge.rglob("*.md")):
        if path.name in SKIP_NAMES:
            continue
        yield path


def rel(knowledge: Path, path: Path) -> str:
    return path.relative_to(knowledge).as_posix()


# --------------------------------------------------------------------------- #
# validate
# --------------------------------------------------------------------------- #


def validate_concept(knowledge: Path, path: Path, today: dt.date) -> tuple[list[str], list[str], dict | None]:
    errors: list[str] = []
    warnings: list[str] = []
    where = rel(knowledge, path)

    if not KEBAB.match(path.name):
        errors.append(f"{where}: file name must be kebab-case .md")

    try:
        fm, body = read_concept(path)
    except ParseError as exc:
        return [f"{where}: frontmatter parse error: {exc}"], warnings, None
    if fm is None:
        return [f"{where}: missing frontmatter"], warnings, None

    for field in REQUIRED_FIELDS:
        if fm.get(field) in (None, "", []):
            errors.append(f"{where}: missing required field `{field}`")

    ctype = fm.get("type")
    if ctype and ctype not in ALL_TYPES:
        errors.append(f"{where}: unknown type `{ctype}`")
    status = fm.get("status")
    if status and status not in STATUSES:
        errors.append(f"{where}: invalid status `{status}`")
    view = fm.get("view")
    if view and view not in VIEWS:
        errors.append(f"{where}: invalid view `{view}`")

    sources = fm.get("sources") or []
    if not isinstance(sources, list):
        errors.append(f"{where}: `sources` must be a list")
        sources = []
    for i, source in enumerate(sources):
        if not isinstance(source, dict):
            errors.append(f"{where}: sources[{i}] must be a mapping")
            continue
        resource = source.get("resource")
        role = source.get("role")
        if not resource:
            errors.append(f"{where}: sources[{i}] missing `resource`")
        elif str(resource).startswith("git+") and "@" not in str(resource):
            errors.append(f"{where}: sources[{i}] git resource must pin a revision with @<rev>")
        if role not in ROLES:
            errors.append(f"{where}: sources[{i}] invalid role `{role}`")

    verified = fm.get("verified") or []
    if verified and not isinstance(verified, list):
        errors.append(f"{where}: `verified` must be a list")
        verified = []
    verifiers = [str(v.get("by", "")) for v in verified if isinstance(v, dict)]

    if status == "stable":
        if not verifiers:
            errors.append(f"{where}: stable requires non-empty `verified`")
        elif ctype in HUMAN_VERIFIED_TYPES and not any(v.startswith("human:") for v in verifiers):
            errors.append(f"{where}: stable {ctype} requires a `human:` verifier")
    if fm.get("generated") and not verifiers and status == "stable":
        errors.append(f"{where}: generated concept without `verified` cannot be stable")

    if ctype in DETAIL_TYPES and not fm.get("expanded_by"):
        errors.append(f"{where}: detail type `{ctype}` requires `expanded_by` (only domain-knowledge-expand may create it)")

    if status == "deprecated" and not fm.get("superseded_by"):
        warnings.append(f"{where}: deprecated without `superseded_by`")

    superseded = fm.get("superseded_by")
    if superseded and not (knowledge / str(superseded)).is_file():
        errors.append(f"{where}: superseded_by target not found: {superseded}")

    stale_after = fm.get("stale_after")
    if stale_after:
        try:
            if dt.date.fromisoformat(str(stale_after)) < today:
                warnings.append(f"{where}: past stale_after {stale_after}")
        except ValueError:
            errors.append(f"{where}: stale_after must be YYYY-MM-DD")

    expected_dir = TYPE_DIR.get(ctype)
    if expected_dir and path.parent.name != expected_dir:
        warnings.append(f"{where}: type `{ctype}` usually lives under `{expected_dir}/`")
    if ctype in ("Bounded Context", "Application") and path.name != "overview.md":
        warnings.append(f"{where}: `{ctype}` is usually the directory's overview.md")

    for target in LINK.findall(body):
        if "://" in target or target.startswith(("#", "mailto:")):
            continue
        link_path = target.split("#", 1)[0]
        if link_path and not (path.parent / link_path).resolve().exists():
            errors.append(f"{where}: broken link {target}")

    return errors, warnings, fm


def detect_supersession_cycles(knowledge: Path, concepts: dict[str, dict]) -> list[str]:
    errors: list[str] = []
    graph = {p: str(fm.get("superseded_by")) for p, fm in concepts.items() if fm.get("superseded_by")}
    for start in graph:
        seen = [start]
        node = graph.get(start)
        while node:
            if node in seen:
                errors.append(f"{start}: superseded_by cycle via {' -> '.join(seen + [node])}")
                break
            seen.append(node)
            node = graph.get(node)
    return errors


def run_validate(bundle: Path, check_index: bool = False, today: dt.date | None = None) -> tuple[list[str], list[str], dict[str, dict]]:
    today = today or dt.date.today()
    knowledge = bundle / "knowledge"
    errors: list[str] = []
    warnings: list[str] = []
    concepts: dict[str, dict] = {}
    for path in iter_concepts(knowledge):
        e, w, fm = validate_concept(knowledge, path, today)
        errors.extend(e)
        warnings.extend(w)
        if fm is not None:
            concepts[rel(knowledge, path)] = fm
    errors.extend(detect_supersession_cycles(knowledge, concepts))
    if check_index:
        for index_path, expected in build_indexes(bundle, concepts).items():
            current = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
            if _index_body(current) != _index_body(expected):
                errors.append(f"{rel(knowledge, index_path)}: out of date, run `kb.py index`")
    return errors, warnings, concepts


# --------------------------------------------------------------------------- #
# index
# --------------------------------------------------------------------------- #


def _index_body(text: str) -> str:
    """Strip the generation timestamp line so comparisons are stable."""
    return "\n".join(l for l in text.splitlines() if not l.startswith("生成于 "))


def _table(rows: list[tuple[str, dict]], base: str) -> list[str]:
    lines = ["| 路径 | type | 摘要 | status | view | owner |", "|---|---|---|---|---|---|"]
    for path, fm in rows:
        link = os.path.relpath(path, base) if base else path
        lines.append(
            "| [{p}]({l}) | {t} | {d} | {s} | {v} | {o} |".format(
                p=path,
                l=link,
                t=fm.get("type", ""),
                d=str(fm.get("description", "")).replace("|", "\\|"),
                s=fm.get("status", ""),
                v=fm.get("view", ""),
                o=fm.get("owner", ""),
            )
        )
    return lines


def build_indexes(bundle: Path, concepts: dict[str, dict]) -> dict[Path, str]:
    knowledge = bundle / "knowledge"
    stamp = dt.date.today().isoformat()
    groups: dict[str, list[tuple[str, dict]]] = {}
    for path, fm in sorted(concepts.items()):
        parts = path.split("/")
        group = "/".join(parts[:2]) if parts[0] in ("domains", "systems") and len(parts) > 2 else parts[0]
        groups.setdefault(group, []).append((path, fm))

    out: dict[Path, str] = {}
    root_lines = [GENERATED_MARK, "# Knowledge Index", "", f"生成于 {stamp}，由 `kb.py index` 维护，请勿手改。", ""]
    counts = {s: 0 for s in STATUSES}
    for fm in concepts.values():
        if fm.get("status") in counts:
            counts[fm["status"]] += 1
    root_lines.append(f"共 {len(concepts)} 条：draft {counts['draft']} · stable {counts['stable']} · deprecated {counts['deprecated']}。`draft` 可用但必须标明未确认；`deprecated` 不参与默认回答。")
    root_lines.append("")
    for group, rows in groups.items():
        root_lines.append(f"## {group}")
        root_lines.append("")
        root_lines.extend(_table(rows, ""))
        root_lines.append("")
        if group.count("/") == 1:
            sub_lines = [GENERATED_MARK, f"# {group}", "", f"生成于 {stamp}，由 `kb.py index` 维护，请勿手改。", ""]
            sub_lines.extend(_table(rows, group))
            sub_lines.append("")
            out[knowledge / group / "index.md"] = "\n".join(sub_lines)
    out[knowledge / "index.md"] = "\n".join(root_lines)
    return out


def run_index(bundle: Path) -> list[Path]:
    errors, _, concepts = run_validate(bundle)
    fatal = [e for e in errors if "frontmatter" in e]
    if fatal:
        sys.exit("\n".join(fatal))
    written = []
    for path, text in build_indexes(bundle, concepts).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


# --------------------------------------------------------------------------- #
# stale
# --------------------------------------------------------------------------- #


def run_stale(bundle: Path, today: dt.date | None = None) -> dict:
    today = today or dt.date.today()
    _, _, concepts = run_validate(bundle, today=today)
    stale = []
    for path, fm in concepts.items():
        value = fm.get("stale_after")
        try:
            if value and dt.date.fromisoformat(str(value)) < today:
                stale.append({"path": path, "stale_after": str(value), "status": fm.get("status")})
        except ValueError:
            continue
    by_status = {s: sum(1 for fm in concepts.values() if fm.get("status") == s) for s in STATUSES}
    return {"total": len(concepts), "by_status": by_status, "stale": stale}


# --------------------------------------------------------------------------- #
# proposals
# --------------------------------------------------------------------------- #


def run_proposals(bundle: Path, queue: bool = False) -> tuple[list[dict], list[str]]:
    proposals_dir = bundle / ".kb" / "proposals"
    queue_dir = bundle / ".kb" / "review-queue"
    items: list[dict] = []
    errors: list[str] = []
    if not proposals_dir.is_dir():
        return items, errors
    for path in sorted(proposals_dir.glob("*.md")):
        try:
            fm, body = read_concept(path)
        except ParseError as exc:
            errors.append(f"{path.name}: {exc}")
            continue
        if fm is None:
            errors.append(f"{path.name}: missing frontmatter")
            continue
        kind = fm.get("kind")
        if kind not in PROPOSAL_KINDS:
            errors.append(f"{path.name}: invalid kind `{kind}`")
        concepts = fm.get("concepts") or []
        if kind != "new" and not concepts:
            errors.append(f"{path.name}: `{kind}` proposal must list affected concepts")
        for c in concepts:
            if not (bundle / "knowledge" / str(c)).is_file():
                errors.append(f"{path.name}: concept not found: {c}")
        sources = fm.get("sources") or []
        if not sources:
            errors.append(f"{path.name}: proposal needs at least one source")
        for i, s in enumerate(sources):
            if not isinstance(s, dict) or s.get("role") not in ROLES:
                errors.append(f"{path.name}: sources[{i}] invalid role")
        if not re.search(r"^(Observed|Derived|Confirmed|Inferred)\b", body, re.MULTILINE):
            errors.append(f"{path.name}: body must mark claims as Observed/Derived/Confirmed/Inferred")
        queued = False
        if queue and kind in QUEUE_KINDS:
            queue_dir.mkdir(parents=True, exist_ok=True)
            target = queue_dir / path.name
            if not target.exists():
                target.write_text(
                    f"---\nkind: {kind}\nproposal: .kb/proposals/{path.name}\nqueued_at: {dt.datetime.now().isoformat(timespec='seconds')}\n---\n\n"
                    f"来自提案 `{path.name}`：{kind} 说明 Bundle 正在误导，需 Owner 处理。\n",
                    encoding="utf-8",
                )
            queued = True
        items.append({"file": path.name, "kind": kind, "concepts": concepts, "queued": queued})
    return items, errors


# --------------------------------------------------------------------------- #
# inventory
# --------------------------------------------------------------------------- #

LANG_EXT = {
    ".java": "java", ".kt": "kotlin", ".py": "python", ".go": "go", ".rs": "rust", ".ts": "typescript",
    ".tsx": "typescript", ".js": "javascript", ".jsx": "javascript", ".c": "c", ".h": "c", ".cpp": "cpp",
    ".cc": "cpp", ".hpp": "cpp", ".cs": "csharp", ".rb": "ruby", ".php": "php", ".scala": "scala",
    ".swift": "swift", ".sql": "sql", ".proto": "protobuf", ".graphql": "graphql",
}
BUILD_ROOTS = {
    "package.json", "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "go.mod",
    "Cargo.toml", "pyproject.toml", "setup.py", "requirements.txt", "CMakeLists.txt", "Makefile",
    "build.sbt", "composer.json", "Gemfile", "*.csproj",
}
CONTRACT_PATTERNS = re.compile(r"(openapi|swagger|asyncapi).*\.(ya?ml|json)$|\.proto$|\.graphql$|\.avsc$|\.wsdl$", re.I)
MIGRATION_DIRS = {"migrations", "migration", "db/migrate", "flyway", "liquibase", "alembic"}
TEST_DIRS = {"test", "tests", "__tests__", "spec", "src/test"}
CI_FILES = {".gitlab-ci.yml", "Jenkinsfile", "azure-pipelines.yml", ".travis.yml"}
ENTRY_HINTS = re.compile(r"^(main|app|server|index|application|cmd)\.[a-z]+$|Application\.(java|kt)$", re.I)
EXCLUDE_DIRS = {".git", "node_modules", "dist", "build", "target", "vendor", ".venv", "venv", "__pycache__", ".idea", ".gradle", "out", "bin", "obj"}


def run_inventory(repo: Path, bundle: Path, name: str | None = None, max_files: int = 50000) -> dict:
    repo = repo.resolve()
    name = name or repo.name
    result: dict[str, Any] = {
        "repository": name,
        "path": str(repo),
        "scanned_at": dt.datetime.now().isoformat(timespec="seconds"),
        "git_head": _git_head(repo),
        "languages": {},
        "build_roots": [],
        "contracts": [],
        "migrations": [],
        "test_dirs": [],
        "ci": [],
        "containers": [],
        "codeowners": None,
        "entry_hints": [],
        "docs": [],
        "truncated": False,
        "unknown_extensions": {},
    }
    count = 0
    for dirpath, dirnames, filenames in os.walk(repo):
        dirnames[:] = sorted(d for d in dirnames if d not in EXCLUDE_DIRS and not d.startswith("."))
        rel_dir = Path(dirpath).relative_to(repo).as_posix()
        rel_dir = "" if rel_dir == "." else rel_dir
        if Path(dirpath).name in MIGRATION_DIRS or rel_dir in MIGRATION_DIRS:
            result["migrations"].append(rel_dir)
        if Path(dirpath).name in TEST_DIRS or rel_dir in TEST_DIRS:
            result["test_dirs"].append(rel_dir)
        for filename in filenames:
            count += 1
            if count > max_files:
                result["truncated"] = True
                break
            rel_path = f"{rel_dir}/{filename}" if rel_dir else filename
            ext = Path(filename).suffix.lower()
            lang = LANG_EXT.get(ext)
            if lang:
                result["languages"][lang] = result["languages"].get(lang, 0) + 1
            elif ext and ext not in (".md", ".txt", ".json", ".yml", ".yaml", ".xml", ".lock", ".png", ".jpg", ".svg"):
                result["unknown_extensions"][ext] = result["unknown_extensions"].get(ext, 0) + 1
            if filename in BUILD_ROOTS or filename.endswith(".csproj"):
                result["build_roots"].append(rel_path)
            if CONTRACT_PATTERNS.search(filename):
                result["contracts"].append(rel_path)
            if filename in CI_FILES or rel_dir.startswith(".github/workflows"):
                result["ci"].append(rel_path)
            if filename.startswith("Dockerfile") or filename in ("docker-compose.yml", "docker-compose.yaml"):
                result["containers"].append(rel_path)
            if filename == "CODEOWNERS":
                result["codeowners"] = rel_path
            if ENTRY_HINTS.search(filename):
                result["entry_hints"].append(rel_path)
            if ext == ".md" and (rel_dir.startswith("docs") or rel_dir.startswith("doc") or not rel_dir):
                result["docs"].append(rel_path)
        if result["truncated"]:
            break
    result["file_count"] = min(count, max_files)
    out_dir = bundle / ".kb" / "inventory"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{name}.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result


def _git_head(repo: Path) -> str | None:
    head = repo / ".git" / "HEAD"
    if not head.is_file():
        return None
    ref = head.read_text(encoding="utf-8").strip()
    if ref.startswith("ref: "):
        ref_path = repo / ".git" / ref[5:]
        if ref_path.is_file():
            return ref_path.read_text(encoding="utf-8").strip()
        packed = repo / ".git" / "packed-refs"
        if packed.is_file():
            for line in packed.read_text(encoding="utf-8").splitlines():
                if line.endswith(" " + ref[5:]):
                    return line.split()[0]
        return None
    return ref


# --------------------------------------------------------------------------- #
# audit / lock / init / log
# --------------------------------------------------------------------------- #


def run_audit(bundle: Path) -> tuple[Path, bool]:
    errors, warnings, concepts = run_validate(bundle, check_index=True)
    stale = run_stale(bundle)
    proposals, proposal_errors = run_proposals(bundle)
    queue_dir = bundle / ".kb" / "review-queue"
    queue = sorted(p.name for p in queue_dir.glob("*.md")) if queue_dir.is_dir() else []
    lock = read_lock(bundle)
    today = dt.date.today().isoformat()
    lines = [
        f"# Audit {today}",
        "",
        f"- Concepts: {stale['total']}（draft {stale['by_status']['draft']} · stable {stale['by_status']['stable']} · deprecated {stale['by_status']['deprecated']}）",
        f"- Errors: {len(errors)}",
        f"- Warnings: {len(warnings)}",
        f"- Past stale_after: {len(stale['stale'])}",
        f"- Pending proposals: {len(proposals)}（invalid {len(proposal_errors)}）",
        f"- Review queue: {len(queue)}",
        f"- Maintenance lock: {'held by ' + str(lock.get('holder')) if lock else 'free'}",
        "",
        "## Errors（回 ingest 修结构）",
        "",
    ]
    lines += [f"- {e}" for e in errors] or ["- none"]
    lines += ["", "## Warnings", ""]
    lines += [f"- {w}" for w in warnings] or ["- none"]
    lines += ["", "## Stale", ""]
    lines += [f"- {s['path']} (stale_after {s['stale_after']}, {s['status']})" for s in stale["stale"]] or ["- none"]
    lines += ["", "## Proposals", ""]
    lines += [f"- {p['file']} [{p['kind']}] → {', '.join(p['concepts']) or '(new)'}" for p in proposals] or ["- none"]
    lines += [f"- INVALID {e}" for e in proposal_errors]
    lines += ["", "## Review queue（回 review 裁语义）", ""]
    lines += [f"- {q}" for q in queue] or ["- none"]
    lines += ["", "## 需人工检查（脚本不判断）", "", "- 未标记 Inferred 的推断", "- AS-IS / TO-BE / historical 混写", "- 同名术语被强制合并", "- 冲突被静默覆盖", "- 敏感材料进入发布层", "- 黄金问题回归（设计场景 / 实现场景）", ""]
    out_dir = bundle / ".kb" / "audit"
    out_dir.mkdir(parents=True, exist_ok=True)
    report = out_dir / f"{today}.md"
    report.write_text("\n".join(lines), encoding="utf-8")
    append_log(bundle, "audit", f"errors={len(errors)} warnings={len(warnings)} stale={len(stale['stale'])} proposals={len(proposals)}")
    return report, not errors and not proposal_errors


def lock_path(bundle: Path) -> Path:
    return bundle / ".kb" / "maintenance.lock"


def read_lock(bundle: Path) -> dict:
    path = lock_path(bundle)
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"holder": "unknown"}


def run_lock(bundle: Path, mode: str, holder: str) -> None:
    lock_path(bundle).parent.mkdir(parents=True, exist_ok=True)
    lock_path(bundle).write_text(
        json.dumps({"mode": mode, "holder": holder, "at": dt.datetime.now().isoformat(timespec="seconds")}, ensure_ascii=False),
        encoding="utf-8",
    )


def run_unlock(bundle: Path) -> bool:
    path = lock_path(bundle)
    if path.is_file():
        path.unlink()
        return True
    return False


def append_log(bundle: Path, mode: str, title: str) -> None:
    log = bundle / "knowledge" / "log.md"
    log.parent.mkdir(parents=True, exist_ok=True)
    if not log.is_file():
        log.write_text("# Log\n\n追加式记录。格式：`## [date] mode | 标题`。\n", encoding="utf-8")
    with log.open("a", encoding="utf-8") as fh:
        fh.write(f"\n## [{dt.date.today().isoformat()}] {mode} | {title}\n")


CONFIG_TEMPLATE = """# Domain Knowledge Bundle 配置
bundle:
  name: {name}
  okf_profile: team-v1
consumers:
  - coding-agent
  - design-agent
freshness:
  business: 90d          # 业务语义默认 stale_after 间隔
  skeleton: 30d          # 实现骨架
  detail: 14d            # expand 产物
review:
  human_required_types:
    - Bounded Context
    - Ubiquitous Term
    - Business Rule
    - Business Process
    - Architecture Decision
  high_risk_tags: [security, payment, permission, release]
expand:
  enabled: false         # 由 domain-knowledge-expand 在被明确请求时改为 true
repositories: []         # bootstrap 时登记：- {{ name, url, default_branch, include, exclude }}
"""

AGENTS_TEMPLATE = """# 领域知识入口

本仓库使用 Domain Knowledge Bundle：`{kb_rel}/knowledge/`。

## 怎么读
1. 先读 `knowledge/index.md`（type、一行摘要、status、view、owner），定位 Bounded Context 与系统。
2. 再读领域 `overview.md` / 系统 `overview.md`，只在判断相关后读少量 Concept。
3. 需要源码级事实时回代码仓、契约、ADR 原文；Bundle 只负责路由、约束、出处。

## 回答规则
- `draft` 可以用，但必须标明"未确认"并给出 Concept 路径；`deprecated` 不参与默认回答。
- 同时有 `stable` 与 `draft` 时结论跟 `stable`。
- 安全、资金、权限、发布规则的 `draft` 只能当候选，不得写成可执行策略。
- `view: to-be` 是目标，不是现状；不与 AS-IS 混答。
- 证据冲突、过期或不足时拒答或找 owner。

## 写入规则
- 任务 Agent 不直接改 `knowledge/`；发现矛盾、路由错误、缺失规则、设计取舍、stable 被推翻时，写提案到 `.kb/proposals/`（见 using-domain-knowledge）。
- 维护动作走 `domain-knowledge-maintain`；`.kb/` 里的材料不是正式结论。
"""


def run_init(bundle: Path, name: str | None = None) -> list[Path]:
    created: list[Path] = []
    dirs = [
        "knowledge/domains", "knowledge/systems", "knowledge/decisions", "knowledge/playbooks", "knowledge/references",
        ".kb/sources", ".kb/inventory", ".kb/proposals", ".kb/conflicts", ".kb/review-queue", ".kb/audit", ".kb/.sessions",
    ]
    for d in dirs:
        path = bundle / d
        if not path.exists():
            path.mkdir(parents=True)
            created.append(path)
    files = {
        ".kb/config.yaml": CONFIG_TEMPLATE.format(name=name or bundle.name),
        ".kb/source-registry.yaml": "sources: []\n",
        "AGENTS.md": AGENTS_TEMPLATE.format(kb_rel="."),
        ".gitignore": ".kb/.sessions/\n.kb/maintenance.lock\n",
    }
    for relpath, content in files.items():
        path = bundle / relpath
        if not path.exists():
            path.write_text(content, encoding="utf-8")
            created.append(path)
    if not (bundle / "knowledge" / "log.md").is_file():
        append_log(bundle, "init", "bundle created")
        created.append(bundle / "knowledge" / "log.md")
    run_index(bundle)
    return created


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="kb.py", description=__doc__)
    parser.add_argument("--bundle", help="bundle root (default: discover)")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("init", help="scaffold a bundle");
    p.add_argument("path"); p.add_argument("--name")
    p = sub.add_parser("validate", help="check concepts against bundle-contract");
    p.add_argument("--check-index", action="store_true"); p.add_argument("--json", action="store_true")
    sub.add_parser("index", help="rebuild index.md files")
    p = sub.add_parser("stale", help="list past stale_after and status counts"); p.add_argument("--json", action="store_true")
    p = sub.add_parser("proposals", help="list and validate .kb/proposals");
    p.add_argument("--queue", action="store_true", help="copy route-error/stale into review-queue"); p.add_argument("--json", action="store_true")
    p = sub.add_parser("inventory", help="static repository inventory into .kb/inventory");
    p.add_argument("repo"); p.add_argument("--name"); p.add_argument("--max-files", type=int, default=50000)
    sub.add_parser("audit", help="full check, write .kb/audit/<date>.md")
    p = sub.add_parser("lock", help="take the maintenance lock so hooks allow writes to knowledge/");
    p.add_argument("mode", choices=["bootstrap", "ingest", "sync", "review", "audit", "expand"]); p.add_argument("--holder", default=os.environ.get("USER", "agent"))
    sub.add_parser("unlock", help="release the maintenance lock")
    p = sub.add_parser("log", help="append a log.md entry"); p.add_argument("mode"); p.add_argument("title")

    args = parser.parse_args(argv)

    if args.cmd == "init":
        bundle = Path(args.path).resolve()
        (bundle / "knowledge").mkdir(parents=True, exist_ok=True)
        created = run_init(bundle, args.name)
        for path in created:
            print(f"created {path.relative_to(bundle)}")
        print(f"bundle ready at {bundle}")
        return 0

    bundle = require_bundle(args.bundle)

    if args.cmd == "validate":
        errors, warnings, concepts = run_validate(bundle, check_index=args.check_index)
        if args.json:
            print(json.dumps({"errors": errors, "warnings": warnings, "concepts": len(concepts)}, ensure_ascii=False, indent=2))
        else:
            for w in warnings:
                print(f"WARN  {w}")
            for e in errors:
                print(f"ERROR {e}")
            print(f"{len(concepts)} concepts, {len(errors)} errors, {len(warnings)} warnings")
        return 1 if errors else 0

    if args.cmd == "index":
        for path in run_index(bundle):
            print(f"wrote {path.relative_to(bundle)}")
        return 0

    if args.cmd == "stale":
        report = run_stale(bundle)
        if args.json:
            print(json.dumps(report, ensure_ascii=False, indent=2))
        else:
            print(f"total {report['total']} · " + " · ".join(f"{k} {v}" for k, v in report["by_status"].items()))
            for s in report["stale"]:
                print(f"STALE {s['path']} ({s['stale_after']}, {s['status']})")
        return 0

    if args.cmd == "proposals":
        items, errors = run_proposals(bundle, queue=args.queue)
        if args.json:
            print(json.dumps({"proposals": items, "errors": errors}, ensure_ascii=False, indent=2))
        else:
            for item in items:
                flag = " → review-queue" if item["queued"] else ""
                print(f"{item['file']} [{item['kind']}] {', '.join(item['concepts']) or '(new)'}{flag}")
            for e in errors:
                print(f"ERROR {e}")
            print(f"{len(items)} proposals, {len(errors)} errors")
        return 1 if errors else 0

    if args.cmd == "inventory":
        result = run_inventory(Path(args.repo), bundle, args.name, args.max_files)
        print(json.dumps({k: result[k] for k in ("repository", "git_head", "file_count", "languages", "build_roots", "contracts", "migrations", "truncated")}, ensure_ascii=False, indent=2))
        print(f"written to .kb/inventory/{result['repository']}.json")
        return 0

    if args.cmd == "audit":
        report, ok = run_audit(bundle)
        print(report.read_text(encoding="utf-8"))
        print(f"report: {report.relative_to(bundle)}")
        return 0 if ok else 1

    if args.cmd == "lock":
        existing = read_lock(bundle)
        if existing:
            print(f"lock already held by {existing.get('holder')} ({existing.get('mode')}, {existing.get('at')})")
            return 1
        run_lock(bundle, args.mode, args.holder)
        print(f"locked for {args.mode} by {args.holder}")
        return 0

    if args.cmd == "unlock":
        print("unlocked" if run_unlock(bundle) else "no lock held")
        return 0

    if args.cmd == "log":
        append_log(bundle, args.mode, args.title)
        print("logged")
        return 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
