"""Tests for domain-knowledge-library/hooks: each script is exercised end to end
with the JSON payload Cursor sends on stdin."""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOKS = ROOT / "domain-knowledge-library" / "hooks"

DRAFT = """---
type: Business Rule
title: 退款限额
description: 退款限额规则。
tags: [payment]
context: billing
view: as-is
owner: team:billing
sources:
  - id: s
    resource: git+https://e/r.git@1#f
    role: implementation
status: draft
---

Inferred  限额为 1000。
"""

STABLE_TOBE = """---
type: Business Process
title: 新履约流程
description: 目标态履约流程。
context: order-fulfillment
view: to-be
owner: team:order
sources:
  - id: s
    resource: docs/design/fulfillment-v2.md
    role: design-intent
verified:
  - by: human:owner
    at: 2026-01-01T00:00:00Z
status: stable
stale_after: 2000-01-01
---

Confirmed  目标流程。
"""


def run_hook(name: str, payload: dict, cwd: Path) -> dict:
    proc = subprocess.run(
        [sys.executable, str(HOOKS / name)],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        cwd=str(cwd),
        env={**os.environ, "CURSOR_PROJECT_DIR": str(cwd)},
        check=False,
    )
    assert proc.returncode == 0, proc.stderr
    return json.loads(proc.stdout.strip() or "{}")


class HookCase(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())
        self.bundle = self.tmp / "bundle"
        for sub in ("knowledge/domains/billing/rules", "knowledge/domains/order-fulfillment/processes", ".kb/proposals", ".kb/.sessions", ".kb/conflicts"):
            (self.bundle / sub).mkdir(parents=True)
        (self.bundle / "knowledge" / "index.md").write_text("<!-- generated by kb.py index -->\n# Knowledge Index\n\n共 2 条：draft 1 · stable 1 · deprecated 0。\n", encoding="utf-8")
        self.draft = self.bundle / "knowledge" / "domains" / "billing" / "rules" / "refund-limit.md"
        self.draft.write_text(DRAFT, encoding="utf-8")
        self.tobe = self.bundle / "knowledge" / "domains" / "order-fulfillment" / "processes" / "fulfillment-v2.md"
        self.tobe.write_text(STABLE_TOBE, encoding="utf-8")
        self.base = {"workspace_roots": [str(self.bundle)], "conversation_id": "conv-1", "cwd": str(self.bundle)}

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def payload(self, **extra):
        data = dict(self.base)
        data.update(extra)
        return data

    def lock(self):
        (self.bundle / ".kb" / "maintenance.lock").write_text(json.dumps({"holder": "maintainer", "mode": "ingest"}), encoding="utf-8")


class TestSessionStart(HookCase):
    def test_injects_entry_when_bundle_present(self):
        out = run_hook("kb_session_start.py", self.payload(session_id="conv-1"), self.bundle)
        ctx = out["additional_context"]
        self.assertIn("knowledge/index.md", ctx)
        self.assertIn("共 2 条", ctx)
        self.assertIn(".kb/proposals/", ctx)

    def test_silent_without_bundle(self):
        empty = self.tmp / "plain"
        empty.mkdir()
        out = run_hook("kb_session_start.py", {"workspace_roots": [str(empty)], "cwd": str(empty)}, empty)
        self.assertEqual(out, {})


class TestReadGuard(HookCase):
    def test_draft_high_risk_reminder_and_session_record(self):
        out = run_hook("kb_read_guard.py", self.payload(tool_name="Read", tool_input={"path": str(self.draft)}), self.bundle)
        ctx = out["additional_context"]
        self.assertIn("draft", ctx)
        self.assertIn("高风险", ctx)
        state = json.loads((self.bundle / ".kb" / ".sessions" / "conv-1.json").read_text(encoding="utf-8"))
        self.assertEqual(state["reads"], ["domains/billing/rules/refund-limit.md"])

    def test_tobe_and_stale_reminder(self):
        out = run_hook("kb_read_guard.py", self.payload(tool_name="Read", tool_input={"path": "knowledge/domains/order-fulfillment/processes/fulfillment-v2.md"}), self.bundle)
        ctx = out["additional_context"]
        self.assertIn("to-be", ctx)
        self.assertIn("stale_after", ctx)

    def test_control_plane_reminder(self):
        conflict = self.bundle / ".kb" / "conflicts" / "x.md"
        conflict.write_text("---\nstatus: open\n---\n", encoding="utf-8")
        out = run_hook("kb_read_guard.py", self.payload(tool_name="Read", tool_input={"path": str(conflict)}), self.bundle)
        self.assertIn("控制面", out["additional_context"])

    def test_index_read_is_silent(self):
        out = run_hook("kb_read_guard.py", self.payload(tool_name="Read", tool_input={"path": str(self.bundle / "knowledge" / "index.md")}), self.bundle)
        self.assertEqual(out, {})

    def test_unrelated_file_is_silent(self):
        other = self.tmp / "other.md"
        other.write_text("---\nstatus: draft\n---\n", encoding="utf-8")
        out = run_hook("kb_read_guard.py", self.payload(tool_name="Read", tool_input={"path": str(other)}), self.bundle)
        self.assertEqual(out, {})


class TestWriteGuard(HookCase):
    def test_knowledge_write_denied_without_lock(self):
        out = run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(self.draft), "contents": "x"}), self.bundle)
        self.assertEqual(out["permission"], "deny")
        self.assertIn(".kb/proposals/", out["agent_message"])

    def test_knowledge_write_allowed_with_lock(self):
        self.lock()
        out = run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(self.draft), "contents": "x"}), self.bundle)
        self.assertEqual(out["permission"], "allow")

    def test_delete_in_knowledge_denied(self):
        out = run_hook("kb_write_guard.py", self.payload(tool_name="Delete", tool_input={"path": str(self.draft)}), self.bundle)
        self.assertEqual(out["permission"], "deny")

    def test_proposal_allowed_and_recorded(self):
        target = self.bundle / ".kb" / "proposals" / "2026-09-03-x.md"
        out = run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(target), "contents": "Observed  fine"}), self.bundle)
        self.assertEqual(out["permission"], "allow")
        state = json.loads((self.bundle / ".kb" / ".sessions" / "conv-1.json").read_text(encoding="utf-8"))
        self.assertEqual(state["proposals"], ["proposals/2026-09-03-x.md"])

    def test_proposal_with_secret_or_email_denied(self):
        target = self.bundle / ".kb" / "proposals" / "2026-09-03-y.md"
        for content in ("Authorization: Bearer abcdefghijklmnopqrstuvwxyz0123456", "contact alice@example.com", "-----BEGIN RSA PRIVATE KEY-----"):
            out = run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(target), "contents": content}), self.bundle)
            self.assertEqual(out["permission"], "deny", content)

    def test_other_control_plane_denied_without_lock(self):
        target = self.bundle / ".kb" / "review-queue" / "x.md"
        out = run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(target), "contents": "x"}), self.bundle)
        self.assertEqual(out["permission"], "deny")

    def test_outside_bundle_allowed(self):
        out = run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(self.tmp / "src" / "a.py"), "contents": "x"}), self.bundle)
        self.assertEqual(out["permission"], "allow")


class TestShellGuard(HookCase):
    def test_redirect_into_knowledge_asks(self):
        out = run_hook("kb_shell_guard.py", self.payload(command="echo hi > knowledge/domains/x.md"), self.bundle)
        self.assertEqual(out["permission"], "ask")

    def test_read_only_command_allowed(self):
        out = run_hook("kb_shell_guard.py", self.payload(command="rg draft knowledge/"), self.bundle)
        self.assertEqual(out["permission"], "allow")

    def test_kb_script_trusted(self):
        out = run_hook("kb_shell_guard.py", self.payload(command="python3 scripts/kb.py index"), self.bundle)
        self.assertEqual(out["permission"], "allow")

    def test_with_lock_allowed(self):
        self.lock()
        out = run_hook("kb_shell_guard.py", self.payload(command="rm knowledge/domains/x.md"), self.bundle)
        self.assertEqual(out["permission"], "allow")


class TestCapturePrompt(HookCase):
    def read_draft(self):
        run_hook("kb_read_guard.py", self.payload(tool_name="Read", tool_input={"path": str(self.draft)}), self.bundle)

    def test_prompts_once_when_reads_without_proposal(self):
        self.read_draft()
        out = run_hook("kb_capture_prompt.py", self.payload(status="completed", loop_count=0), self.bundle)
        self.assertIn("followup_message", out)
        self.assertIn("refund-limit.md", out["followup_message"])
        again = run_hook("kb_capture_prompt.py", self.payload(status="completed", loop_count=0), self.bundle)
        self.assertEqual(again, {})

    def test_silent_when_proposal_written(self):
        self.read_draft()
        run_hook("kb_write_guard.py", self.payload(tool_name="Write", tool_input={"path": str(self.bundle / ".kb" / "proposals" / "p.md"), "contents": "Observed  x"}), self.bundle)
        out = run_hook("kb_capture_prompt.py", self.payload(status="completed", loop_count=0), self.bundle)
        self.assertEqual(out, {})

    def test_silent_when_nothing_read_or_aborted_or_looping(self):
        self.assertEqual(run_hook("kb_capture_prompt.py", self.payload(status="completed", loop_count=0), self.bundle), {})
        self.read_draft()
        self.assertEqual(run_hook("kb_capture_prompt.py", self.payload(status="aborted", loop_count=0), self.bundle), {})
        self.assertEqual(run_hook("kb_capture_prompt.py", self.payload(status="completed", loop_count=1), self.bundle), {})

    def test_silent_during_maintenance(self):
        self.read_draft()
        self.lock()
        self.assertEqual(run_hook("kb_capture_prompt.py", self.payload(status="completed", loop_count=0), self.bundle), {})


class TestInstall(HookCase):
    def test_install_merges_hooks_json_and_copies_scripts(self):
        target = self.tmp / "repo"
        (target / ".cursor").mkdir(parents=True)
        (target / ".cursor" / "hooks.json").write_text(json.dumps({"version": 1, "hooks": {"stop": [{"command": "echo other"}]}}), encoding="utf-8")
        proc = subprocess.run(["bash", str(HOOKS / "install.sh"), str(target)], capture_output=True, text=True, check=False)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        merged = json.loads((target / ".cursor" / "hooks.json").read_text(encoding="utf-8"))
        stop_commands = [e["command"] for e in merged["hooks"]["stop"]]
        self.assertIn("echo other", stop_commands)
        self.assertTrue(any("domain-kb/kb_capture_prompt.py" in c for c in stop_commands))
        self.assertTrue((target / ".cursor" / "hooks" / "domain-kb" / "kb_common.py").is_file())
        proc = subprocess.run(["bash", str(HOOKS / "install.sh"), str(target)], capture_output=True, text=True, check=False)
        merged = json.loads((target / ".cursor" / "hooks.json").read_text(encoding="utf-8"))
        self.assertEqual(sum("domain-kb/" in e["command"] for e in merged["hooks"]["stop"]), 1)


if __name__ == "__main__":
    unittest.main()
